// Daftar bank Indonesia — sumber: Bank Indonesia
// Format: { code: kode bank, name: nama bank }
export const INDONESIAN_BANKS = [
  { code: "002", name: "Bank Rakyat Indonesia (BRI)" },
  { code: "008", name: "Bank Mandiri" },
  { code: "009", name: "Bank Negara Indonesia (BNI)" },
  { code: "011", name: "Bank Danamon" },
  { code: "013", name: "Bank Permata" },
  { code: "014", name: "Bank Central Asia (BCA)" },
  { code: "016", name: "Bank Maybank Indonesia" },
  { code: "019", name: "Bank Panin" },
  { code: "022", name: "Bank CIMB Niaga" },
  { code: "023", name: "Bank UOB Indonesia" },
  { code: "026", name: "Bank OCBC NISP" },
  { code: "028", name: "Bank BTN" },
  { code: "030", name: "American Express Bank" },
  { code: "031", name: "Citibank" },
  { code: "032", name: "Bank of America" },
  { code: "036", name: "Bank Tabungan Pensiunan Nasional (BTPN)" },
  { code: "037", name: "Bank Artha Graha" },
  { code: "040", name: "Bank Bangkok" },
  { code: "042", name: "Bank Mizuho Indonesia" },
  { code: "045", name: "Bank Sumitomo Mitsui Indonesia" },
  { code: "047", name: "Bank Deutsche Indonesia" },
  { code: "048", name: "Bank Resona Perdania" },
  { code: "052", name: "ABN AMRO Bank" },
  { code: "054", name: "Bank ING Indonesia" },
  { code: "055", name: "Standard Chartered" },
  { code: "057", name: "Rabobank International Indonesia" },
  { code: "061", name: "Bank ANZ" },
  { code: "069", name: "Bank of China" },
  { code: "076", name: "Bank Bumi Arta" },
  { code: "087", name: "Bank HSBC Indonesia" },
  { code: "089", name: "Bank Rabobank" },
  { code: "093", name: "Bank IFI" },
  { code: "095", name: "Bank Duta" },
  { code: "097", name: "Bank Mestika Dharma" },
  { code: "098", name: "Bank Sri Partha" },
  { code: "101", name: "Bank Victoria International" },
  { code: "110", name: "Bank BJB" },
  { code: "111", name: "Bank DKI" },
  { code: "112", name: "Bank BPD DIY" },
  { code: "113", name: "Bank Jateng" },
  { code: "114", name: "Bank Jatim" },
  { code: "115", name: "Bank BPD Jambi" },
  { code: "116", name: "Bank Aceh" },
  { code: "117", name: "Bank Sumut" },
  { code: "118", name: "Bank Nagari (Sumbar)" },
  { code: "119", name: "Bank Riau Kepri" },
  { code: "120", name: "Bank Sumsel Babel" },
  { code: "121", name: "Bank BPD Lampung" },
  { code: "122", name: "Bank Kaltimtara" },
  { code: "123", name: "Bank Kalbar" },
  { code: "124", name: "Bank Kalteng" },
  { code: "125", name: "Bank Kalsel" },
  { code: "126", name: "Bank Sulselbar" },
  { code: "127", name: "Bank Sulut Go" },
  { code: "128", name: "Bank NTB Syariah" },
  { code: "129", name: "Bank BPD Bali" },
  { code: "130", name: "Bank BPD NTT" },
  { code: "131", name: "Bank Maluku Malut" },
  { code: "132", name: "Bank Papua" },
  { code: "133", name: "Bank Bengkulu" },
  { code: "134", name: "Bank Sulteng" },
  { code: "135", name: "Bank Sultenggara" },
  { code: "145", name: "Bank Nusantara Parahyangan" },
  { code: "146", name: "Bank of India Indonesia" },
  { code: "147", name: "Bank Muamalat Indonesia" },
  { code: "151", name: "Bank Mega" },
  { code: "152", name: "Bank Haga" },
  { code: "153", name: "Bank Ina Perdana" },
  { code: "157", name: "Bank Harfa" },
  { code: "159", name: "Bank Hagakita" },
  { code: "161", name: "Bank Ganesha" },
  { code: "163", name: "Bank Windu Kentjana" },
  { code: "166", name: "Bank Lippo" },
  { code: "167", name: "Bank Maspion" },
  { code: "168", name: "Bank Bukopin" },
  { code: "169", name: "Bank BRI Syariah" },
  { code: "171", name: "Bank Kesawan" },
  { code: "172", name: "Bank Tabungan Negara Syariah (BTN Syariah)" },
  { code: "200", name: "Bank Tabungan Negara (BTN)" },
  { code: "212", name: "Bank Woori Saudara" },
  { code: "213", name: "Bank BTPN Syariah" },
  { code: "405", name: "Bank BCA Syariah" },
  { code: "410", name: "Bank Jabar Banten Syariah" },
  { code: "411", name: "Bank BNI Syariah" },
  { code: "412", name: "Bank Mandiri Syariah" },
  { code: "413", name: "Bank Mega Syariah" },
  { code: "422", name: "Bank BPD DIY Syariah" },
  { code: "425", name: "Bank Victoria Syariah" },
  { code: "426", name: "Bank Panin Syariah" },
  { code: "427", name: "Bank BRI Agroniaga" },
  { code: "441", name: "Bank Bukopin Syariah" },
  { code: "451", name: "Bank Syariah Indonesia (BSI)" },
  { code: "472", name: "Bank BPD Banten" },
  { code: "484", name: "Bank KEB Hana Indonesia" },
  { code: "485", name: "Bank MNC" },
  { code: "490", name: "Bank Neo Commerce (BNC)" },
  { code: "494", name: "Bank Jago" },
  { code: "503", name: "Bank Nobu (Nationalnobu)" },
  { code: "506", name: "Bank Mega Syariah" },
  { code: "513", name: "Bank Ina Perdana" },
  { code: "517", name: "Bank QNB Indonesia" },
  { code: "521", name: "Bank Bca Digital (blu)" },
  { code: "523", name: "Bank Amar Indonesia" },
  { code: "525", name: "Bank Digital BCA" },
  { code: "526", name: "Seabank Indonesia" },
  { code: "531", name: "Bank Sahabat Sampoerna" },
  { code: "535", name: "Bank Shinhan Indonesia" },
  { code: "536", name: "Bank BRI Agro" },
  { code: "542", name: "Bank Aladin Syariah" },
  { code: "547", name: "Bank Raya Indonesia" },
  { code: "548", name: "Bank Net Indonesia Syariah" },
  { code: "553", name: "Bank SMBC Indonesia" },
  { code: "555", name: "Allo Bank" },
  { code: "559", name: "Bank Hibank Indonesia" },
  { code: "567", name: "Bank Superbank" },
  { code: "568", name: "Bank Saqu (Bank Jago)" },
  { code: "700", name: "Tabungan Pos Indonesia" },
  { code: "911", name: "GoPay" },
  { code: "912", name: "OVO" },
  { code: "913", name: "DANA" },
  { code: "914", name: "ShopeePay" },
  { code: "915", name: "LinkAja" },
].sort((a, b) => a.name.localeCompare(b.name));
