// Fallback data untuk gambar kategori (digunakan sebagai image fallback saja, count dari DB)
export const CATEGORIES = [
  { id: 1, name: "Kerajinan Batu", slug: "kerajinan-batu", icon: "🗿", image: "/images/cat-batu.jpg" },
  { id: 2, name: "Batik & Kain", slug: "batik-kain", icon: "🧵", image: "/images/cat-batik.jpg" },
  { id: 3, name: "Ukiran Kayu", slug: "ukiran-kayu", icon: "🪵", image: "/images/cat-kayu.jpg" },
  { id: 4, name: "Perhiasan & Logam", slug: "perhiasan-logam", icon: "💫", image: "/images/cat-logam.jpg" },
  { id: 5, name: "Fotografi", slug: "fotografi", icon: "📷", image: "/images/cat-fotografi.jpg" },
  { id: 6, name: "Wayang & Topeng", slug: "wayang-topeng", icon: "🎭", image: "/images/cat-wayang.jpg" },
  { id: 7, name: "Keramik & Gerabah", slug: "keramik-gerabah", icon: "🏺", image: "/images/cat-keramik.jpg" },
  { id: 8, name: "Tas & Aksesoris", slug: "tas-aksesoris", icon: "👜", image: "/images/cat-tas.jpg" },
  { id: 9, name: "Lukisan", slug: "lukisan", icon: "🎨", image: "/images/cat-lukisan.jpg" },
  { id: 10, name: "Lainnya", slug: "lainnya", icon: "✨", image: "/images/cat-lainnya.jpg" },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "Patung Ganesha Batu Andesit",
    slug: "patung-ganesha-batu-andesit",
    price: 4500000,
    originalPrice: 5200000,
    image: "/images/product-1.svg",
    images: ["/images/product-1.svg", "/images/product-1b.svg"],
    category: "kerajinan-batu",
    seller: { name: "Mas Budi Jogja", avatar: "/images/seller-1.svg", location: "Yogyakarta", rating: 4.9, sold: 87 },
    rating: 4.9,
    reviews: 124,
    sold: 87,
    isPhygital: true,
    isVerified: true,
    isFeatured: true,
    material: "Batu Andesit",
    dimensions: "30 x 20 x 45 cm",
    weight: "12 kg",
    origin: "Jawa Tengah",
    description: "Patung Ganesha asli buatan tangan pengrajin Yogyakarta dengan batu andesit pilihan. Disertai sertifikat keaslian digital.",
    tags: ["patung", "ganesha", "batu", "jogja"],
    stock: 3,
    hasCertificate: true,
    certificateId: "MAJA-0001-GSH",
  },
  {
    id: 2,
    name: "Batik Mega Mendung Cirebon Silk",
    slug: "batik-mega-mendung-cirebon-silk",
    price: 850000,
    originalPrice: null,
    image: "/images/product-2.svg",
    images: ["/images/product-2.svg"],
    category: "batik-kain",
    seller: { name: "Batik Pusaka Cirebon", avatar: "/images/seller-2.svg", location: "Cirebon", rating: 4.8, sold: 342 },
    rating: 4.8,
    reviews: 89,
    sold: 342,
    isPhygital: true,
    isVerified: true,
    isFeatured: true,
    material: "Sutra",
    dimensions: "200 x 110 cm",
    weight: "0.3 kg",
    origin: "Jawa Barat",
    description: "Batik Mega Mendung khas Cirebon dengan motif awan yang megah. Dibuat dengan teknik tulis tangan oleh pengrajin berpengalaman.",
    tags: ["batik", "mega mendung", "cirebon", "sutra"],
    stock: 15,
    hasCertificate: true,
    certificateId: "MAJA-0002-BMM",
  },
  {
    id: 3,
    name: "Topeng Barong Kayu Jati Ukir",
    slug: "topeng-barong-kayu-jati-ukir",
    price: 1200000,
    originalPrice: 1500000,
    image: "/images/product-3.svg",
    images: ["/images/product-3.svg"],
    category: "wayang-topeng",
    seller: { name: "Seniman Bali Asli", avatar: "/images/seller-3.svg", location: "Bali", rating: 5.0, sold: 56 },
    rating: 5.0,
    reviews: 56,
    sold: 56,
    isPhygital: true,
    isVerified: true,
    isFeatured: false,
    material: "Kayu Jati",
    dimensions: "25 x 18 x 12 cm",
    weight: "1.2 kg",
    origin: "Bali",
    description: "Topeng Barong ukiran kayu jati asli Bali, dibuat oleh seniman berpengalaman dengan detail yang sangat halus.",
    tags: ["topeng", "barong", "bali", "kayu jati"],
    stock: 5,
    hasCertificate: true,
    certificateId: "MAJA-0003-TBR",
  },
  {
    id: 4,
    name: "Gelang Perak Motif Kawung Solo",
    slug: "gelang-perak-motif-kawung-solo",
    price: 320000,
    originalPrice: null,
    image: "/images/product-4.svg",
    images: ["/images/product-4.svg"],
    category: "perhiasan-logam",
    seller: { name: "Perak Kotagede", avatar: "/images/seller-4.svg", location: "Solo", rating: 4.7, sold: 215 },
    rating: 4.7,
    reviews: 201,
    sold: 215,
    isPhygital: false,
    isVerified: true,
    isFeatured: false,
    material: "Perak 925",
    dimensions: "Diameter 6 cm",
    weight: "0.05 kg",
    origin: "Jawa Tengah",
    description: "Gelang perak sterling 925 dengan ukiran motif kawung klasik asal Solo. Cocok sebagai koleksi maupun hadiah.",
    tags: ["gelang", "perak", "kawung", "solo"],
    stock: 30,
    hasCertificate: false,
    certificateId: null,
  },
  {
    id: 5,
    name: "Kain Tenun Ikat NTT Flores",
    slug: "kain-tenun-ikat-ntt-flores",
    price: 680000,
    originalPrice: 780000,
    image: "/images/product-5.svg",
    images: ["/images/product-5.svg"],
    category: "batik-kain",
    seller: { name: "Tenun Flores Asli", avatar: "/images/seller-5.svg", location: "NTT", rating: 4.9, sold: 128 },
    rating: 4.9,
    reviews: 67,
    sold: 128,
    isPhygital: true,
    isVerified: true,
    isFeatured: false,
    material: "Kapas Alam",
    dimensions: "220 x 60 cm",
    weight: "0.4 kg",
    origin: "Nusa Tenggara Timur",
    description: "Kain tenun ikat asli dari Flores, NTT. Dibuat dengan teknik tradisional menggunakan pewarna alami.",
    tags: ["tenun", "ikat", "flores", "ntt"],
    stock: 8,
    hasCertificate: true,
    certificateId: "MAJA-0005-TIF",
  },
  {
    id: 6,
    name: "Wayang Kulit Set Pandawa Lima",
    slug: "wayang-kulit-set-pandawa-lima",
    price: 2800000,
    originalPrice: null,
    image: "/images/product-6.svg",
    images: ["/images/product-6.svg"],
    category: "wayang-topeng",
    seller: { name: "Dalang Surakarta", avatar: "/images/seller-6.svg", location: "Solo", rating: 5.0, sold: 23 },
    rating: 5.0,
    reviews: 23,
    sold: 23,
    isPhygital: true,
    isVerified: true,
    isFeatured: true,
    material: "Kulit Sapi Samak",
    dimensions: "5 buah, tinggi 40-50 cm",
    weight: "1.5 kg",
    origin: "Jawa Tengah",
    description: "Set wayang kulit Pandawa Lima buatan pengrajin wayang berpengalaman dari Solo. Tatahan halus dengan cat emas asli.",
    tags: ["wayang", "kulit", "pandawa", "solo"],
    stock: 2,
    hasCertificate: true,
    certificateId: "MAJA-0006-WPL",
  },
  {
    id: 7,
    name: "Gerabah Majapahit Replika Premium",
    slug: "gerabah-majapahit-replika-premium",
    price: 450000,
    originalPrice: 550000,
    image: "/images/product-7.svg",
    images: ["/images/product-7.svg"],
    category: "keramik-gerabah",
    seller: { name: "Gerabah Trowulan", avatar: "/images/seller-7.svg", location: "Mojokerto", rating: 4.6, sold: 167 },
    rating: 4.6,
    reviews: 88,
    sold: 167,
    isPhygital: true,
    isVerified: false,
    isFeatured: false,
    material: "Tanah Liat Trowulan",
    dimensions: "20 x 20 x 35 cm",
    weight: "2.5 kg",
    origin: "Jawa Timur",
    description: "Replika premium gerabah era Majapahit dari tanah liat asli Trowulan. Dibuat manual tanpa cetakan mesin.",
    tags: ["gerabah", "majapahit", "trowulan", "mojokerto"],
    stock: 12,
    hasCertificate: true,
    certificateId: "MAJA-0007-GMJ",
  },
  {
    id: 8,
    name: "Kebaya Encim Nyonya Betawi",
    slug: "kebaya-encim-nyonya-betawi",
    price: 1350000,
    originalPrice: 1600000,
    image: "/images/product-8.svg",
    images: ["/images/product-8.svg"],
    category: "pakaian-tradisional",
    seller: { name: "Kebaya Betawi Heritage", avatar: "/images/seller-8.svg", location: "Jakarta", rating: 4.8, sold: 94 },
    rating: 4.8,
    reviews: 74,
    sold: 94,
    isPhygital: false,
    isVerified: true,
    isFeatured: false,
    material: "Brokat & Sutra",
    dimensions: "XS, S, M, L, XL",
    weight: "0.5 kg",
    origin: "DKI Jakarta",
    description: "Kebaya encim nyonya khas Betawi dengan bordir bunga halus. Tersedia berbagai ukuran.",
    tags: ["kebaya", "encim", "betawi", "jakarta"],
    stock: 20,
    hasCertificate: false,
    certificateId: null,
  },
];

export const FEATURED_BANNERS = [
  {
    id: 1,
    title: "Ruang Budaya",
    subtitle: "Telusuri artikel budaya, cerita karya seniman, dan acara komunitas seni Indonesia",
    cta: "Jelajahi Budaya",
    href: "/ruang-budaya",
    cta2: "Lihat Acara",
    href2: "/ruang-budaya",
    image: "/images/banner-ruang-budaya.jpg",
    accent: "Komunitas & Event",
  },
  {
    id: 2,
    title: "Batik Warisan Dunia",
    subtitle: "Koleksi batik tulis tangan langsung dari pengrajin asli",
    cta: "Lihat Koleksi Batik",
    href: "/produk?kategori=batik-kain",
    cta2: "Jual Karya",
    href2: "/studio",
    image: "/images/banner-2.jpg",
    accent: "UNESCO Heritage",
  },
  {
    id: 3,
    title: "Kerajinan Batu Candi",
    subtitle: "Ukiran batu andesit bergaya Majapahit oleh maestro Jawa",
    cta: "Belanja Sekarang",
    href: "/produk?kategori=kerajinan-batu",
    cta2: "Jual Karya",
    href2: "/studio",
    image: "/images/banner-3.jpg",
    accent: "Sertifikat Digital",
  },
];

export const formatRupiah = (amount: number): string => {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

export const formatNumber = (num: number): string => {
  if (num >= 1000) return (num / 1000).toFixed(1) + "rb";
  return num.toString();
};
